# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: torre_control.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "torreDeControl.HelloRequest" do
    optional :name, :string, 1
  end
  add_message "torreDeControl.HelloReply" do
    optional :message, :string, 1
  end
end

module TorreDeControl
  HelloRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("torreDeControl.HelloRequest").msgclass
  HelloReply = Google::Protobuf::DescriptorPool.generated_pool.lookup("torreDeControl.HelloReply").msgclass
end
