# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: torre_control.proto for package 'torreDeControl'

require 'grpc'
require 'torre_control_pb'

module TorreDeControl
  module Control
    # The greeting service definition.
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'torreDeControl.Control'

      # Sends a greeting
      rpc :SayHello, HelloRequest, HelloReply
    end

    Stub = Service.rpc_stub_class
  end
end
